import type { ScoutProspect } from "@/types/scouting";

export const mockProspects: ScoutProspect[] = [
  {
    id: "mock-karsiak",
    riotId: "Karsiak#AURA",
    region: "NA",
    role: "JUNGLE",
    score: 91,
    pipelineStage: "TRYOUT",
    statusNote: "Mechanics plus early pathing fit the current academy needs.",
    soloQ: { queue: "SOLOQ", tier: "CHALLENGER", division: "I", lp: 712, wins: 184, losses: 131, winrate: 58.4 },
    flex: { queue: "FLEX", tier: "MASTER", division: "I", lp: 244, wins: 62, losses: 41, winrate: 60.2 },
    championPool: [
      { championName: "Lee Sin", games: 22, winrate: 64.1, kda: 4.2, trend: "up" },
      { championName: "Vi", games: 18, winrate: 61.8, kda: 3.8, trend: "stable" },
      { championName: "Nidalee", games: 12, winrate: 58.3, kda: 4.6, trend: "up" },
    ],
    radar: [
      { axis: "Mechanics", value: 92 },
      { axis: "Laning", value: 70 },
      { axis: "Teamfight", value: 84 },
      { axis: "Pool", value: 82 },
      { axis: "Consistency", value: 78 },
      { axis: "Vision", value: 86 },
    ],
  },
  {
    id: "mock-nexus",
    riotId: "NexusFall#NA1",
    region: "NA",
    role: "MID",
    score: 86,
    pipelineStage: "CONTACTED",
    statusNote: "Control mage specialist, strong comms, Quebec culture fit.",
    soloQ: { queue: "SOLOQ", tier: "GRANDMASTER", division: "I", lp: 522, wins: 146, losses: 112, winrate: 56.6 },
    flex: { queue: "FLEX", tier: "DIAMOND", division: "I", lp: 88, wins: 39, losses: 28, winrate: 58.2 },
    championPool: [
      { championName: "Azir", games: 19, winrate: 63.2, kda: 4.1, trend: "up" },
      { championName: "Orianna", games: 16, winrate: 57.4, kda: 3.7, trend: "stable" },
      { championName: "Viktor", games: 13, winrate: 54.8, kda: 3.5, trend: "stable" },
    ],
    radar: [
      { axis: "Mechanics", value: 82 },
      { axis: "Laning", value: 88 },
      { axis: "Teamfight", value: 86 },
      { axis: "Pool", value: 76 },
      { axis: "Consistency", value: 84 },
      { axis: "Vision", value: 74 },
    ],
  },
  {
    id: "mock-tidal",
    riotId: "TidalWave#NA1",
    region: "NA",
    role: "BOT",
    score: 84,
    pipelineStage: "WATCHING",
    statusNote: "High ceiling ADC profile with lane pressure and carry damage.",
    soloQ: { queue: "SOLOQ", tier: "MASTER", division: "I", lp: 418, wins: 132, losses: 101, winrate: 56.7 },
    flex: { queue: "FLEX", tier: "EMERALD", division: "I", lp: 77, wins: 28, losses: 21, winrate: 57.1 },
    championPool: [
      { championName: "Jinx", games: 21, winrate: 66.7, kda: 4.8, trend: "up" },
      { championName: "Caitlyn", games: 18, winrate: 61.1, kda: 3.9, trend: "up" },
      { championName: "Ezreal", games: 11, winrate: 54.5, kda: 3.6, trend: "down" },
    ],
    radar: [
      { axis: "Mechanics", value: 88 },
      { axis: "Laning", value: 86 },
      { axis: "Teamfight", value: 80 },
      { axis: "Pool", value: 74 },
      { axis: "Consistency", value: 72 },
      { axis: "Vision", value: 58 },
    ],
  },
];
